### ISSUE TITLE
no matching manifest for linux/arm64/v8

### ISSUE THREAD

**Issue by Chenjlin28** [klavinslab/aquarium-local#4]
Describe the bug
Aquarium-local no matching manifest for linux/arm64/v8 in the manifest list entries

To Reproduce
I followed the instruction to install the aquarium from https://aquariumbio.github.io/aquarium-local/, and
./aquarium.sh up
gives me the error.

Expected behavior
I would expect to install it without any error.

Screenshots
![image](https://user-images.githubusercontent.com/65782211/154284262-659632ba-07c3-4a73-af4b-671ea49dada5.png)

Computer/Device (please complete the following information):
OS: [ macOS Big Sur]

**Comment by bjkeller** [comment]
The aquarium Docker build doesn't include manifests for different processors. This would have to be handled in aquariumbio/aquarium.

________________________________
From: Chenjlin28 ***@***.***>
Sent: Wednesday, February 16, 2022 6:25 AM
To: aquariumbio/aquarium-local ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [aquariumbio/aquarium-local] no matching manifest for linux/arm64/v8 (Issue #4)


Describe the bug
Aquarium-local no matching manifest for linux/arm64/v8 in the manifest list entries

To Reproduce
I followed the instruction to install the aquarium from https://aquariumbio.github.io/aquarium-local/, and
./aquarium.sh up
gives me the error.

Expected behavior
I would expect to install it without any error.

Screenshots
[image]<https://user-images.githubusercontent.com/65782211/154284262-659632ba-07c3-4a73-af4b-671ea49dada5.png>

Computer/Device (please complete the following information):
OS: [ macOS Big Sur]

**Comment by Chenjlin28** [comment]
> 水族馆Docker构建不包括不同处理器的清单。这必须在水族馆/水族馆处理。
> [...](#)

Thanks for your answer！ I wonder whether it means I could use Aquarium-local on Window or linux right now, or I can run a Aquarium on my own server.

**Comment by bjkeller** [comment]
It may be that the image needs to be updated. I switched projects at the end of last summer.  But it had been running successfully in different environments: intel Mac, VMs on servers, and Windows being ones I know of.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Chenjlin28** [comment]
> It may be that the image needs to be updated. I switched projects at the end of last summer. But it had been running successfully in different environments: intel Mac, VMs on servers, and Windows being ones I know of. Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

Oh, So this bug maybe due to my Mac mini which using an apple M1 chip, I will try again on another computer running Windows system.
